### ISSUE TITLE
反佣插件时间显示问题

### ISSUE THREAD

**Issue by holyapi** [fjwpsyb/Bncr_plugin#6]
在发送
【京东】[https://3.cn/21-bUN5Y「宠百思](https://3.cn/21-bUN5Y%E3%80%8C%E5%AE%A0%E7%99%BE%E6%80%9D) 狗狗一次性手套拾便袋宠物捡屎袋宠物垃圾袋50片 拾便袋-50片」
返佣插件运行且回复的 仅供参考里的当前价与到手价显示为
：
京东(当前)：
最低价【1970-01-01】【15.68】

到手价：
最低价【1970-01-01】【15.68】

**Comment by holyapi** [comment]
在发送 
【京东】https://3.cn/21-bUN5Y「宠百思 狗狗一次性手套拾便袋宠物捡屎袋宠物垃圾袋50片 拾便袋-50片」
返佣插件运行且回复的 仅供参考里的当前价与到手价显示为
：
京东(当前)：
 最低价【1970-01-01】【15.68】
 
到手价：
 最低价【1970-01-01】【15.68】

**Comment by fjwpsyb** [comment]
![image](https://github.com/fjwpsyb/Bncr_plugin/assets/59650803/43da6c0c-09e3-40d6-ac6c-327dd2d01151)

fix
