### ISSUE TITLE
future issue

### ISSUE THREAD

**Issue by holyapi** [fjwpsyb/Bncr_plugin#7]
返佣脚本：
在转链京东国际等不支持转链的商品只后输出原商品链接 以及比价与历史价格功能

**Comment by fjwpsyb** [comment]
比如？

**Comment by holyapi** [comment]
比如在转连 https://3.cn/21euh-4j 时 不支持推广的商品只进行比价与历史价格功能
![image](https://github.com/fjwpsyb/Bncr_plugin/assets/164745110/53088068-e67a-4457-bc4a-b9f907bc44f0)
而不是输出查询失败
